In [2]:
import numpy as np

A = np.array([
    [3, 1],
    [2, 0]
])

B = np.array([
    [2, 1],
    [1, -1]
])

hasil_AB = np.dot(A, B)

print("Hasil A x B:")
print(hasil_AB)

Hasil A x B:
[[7 2]
 [4 2]]


In [3]:
import numpy as np

B = np.array([
    [2, 1],
    [1, -1]
])

C = np.array([
    [-1, 1, 2],
    [2, 0, -1]
])

hasil_BC = np.dot(B, C)

print("Hasil B x C:")
print(hasil_BC)

Hasil B x C:
[[ 0  2  3]
 [-3  1  3]]


In [4]:
import math

hasil_1 = math.factorial(6)
hasil_2 = math.factorial(8) // math.factorial(5)

print(hasil_1)
print(hasil_2)

720
336


In [1]:
import numpy as np

# Membuat vektor A dan B
A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

# Menghitung panjang vektor
panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

# Menghitung dot product
hasil_dot = np.dot(A, B)

# Menghitung cross product
hasil_cross = np.cross(A, B)

# Menampilkan hasil
print("Panjang vektor A =", panjang_A)
print("Panjang vektor B =", panjang_B)
print("Hasil A . B =", hasil_dot)
print("Hasil A x B =", hasil_cross)

Panjang vektor A = 9.1104335791443
Panjang vektor B = 12.409673645990857
Hasil A . B = 58
Hasil A x B = [ 24  79 -51]
